theme = "native"
icons = "awesome5"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_total_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0


[[block]]
block = "nvidia_gpu"
label = "RTX 3050Ti"
show_memory = true
show_clocks = true
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

# [[block]]
# block = "xrandr"
# icons = true
# resolution = true
# interval = 2

# [[block]]
# block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"
